site_name: enabel/user-bundle
site_description: Symfony User management

repo_name: enabel/user-bundle
repo_url: https://github.com/Enabel/user-bundle
edit_uri: https://github.com/Enabel/user-bundle/edit/main/docs/

theme:
  name: readthedocs
  language: en

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/enabel/user-bundle
      name: enabel/user-bundle repository
  generator: false

plugins:
  - search: { }

nav:
  - Installation: 'index.md'
  - Authentication: 'authentication.md'
  - Command: 'command.md'
  - EasyAdmin: 'easyadmin.md'
  - 'Bug tracker': 'https://github.com/Enabel/user-bundle/issues'
