enabel_user:
  resource: "../src/Controller/"
  type: attribute

forgot_password:
  path: /forgot_password
  controller: Enabel\UserBundle\Controller\AccountController::forgotPassword
  defaults:
    _locale: '%locale%'