name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          tools: symfony, composer:v2
          extensions: gd,json,iconv,intl,mbstring,pdo,pdo_mysql,xml,zip,curl,apcu

      - name: Install Composer dependencies
        run: |
          composer validate --no-check-publish
          composer install --prefer-dist --no-progress --optimize-autoloader --no-interaction

      - name: Cleanup build
        run: |
          rm -Rf .git/

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: ${{ github.workspace }}
          compression-level: 9

  security:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          tools: symfony
          extensions: gd,json,iconv,intl,mbstring,pdo,pdo_mysql,xml,zip,curl,apcu

      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: build
          path: .

      - name: Security checker
        run: symfony check:security

  coding-standards:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          tools: symfony
          extensions: gd,json,iconv,intl,mbstring,pdo,pdo_mysql,xml,zip,curl,apcu

      - name: Download package
        uses: actions/download-artifact@v4
        with:
          name: build
          path: .

      - name: Run php_codesniffer with PSR12 standard
        run: composer cs

      - name: Run PHPStan
        run: composer stan

      - name: Run PHP Insights
        run: composer insight

  tests:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          tools: symfony
          extensions: gd,json,iconv,intl,mbstring,pdo,pdo_mysql,xml,zip,curl,apcu
          coverage: xdebug

      - name: Download package
        uses: actions/download-artifact@v4
        with:
          name: build
          path: .

      - name: All Tests (unit & functional)
        run: composer test

      - name: Publish coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        with:
          directory: coverage

  Cleanup:
    needs: [build, security, coding-standards, tests]
    runs-on: ubuntu-latest
    steps:
      - name: Clean up artifacts
        uses: geekyeggo/delete-artifact@v4
        with:
          name: build
